config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contact_us, only: [:new, :create, :show]
  get '/invisible_recaptcha_new', to: 'contact_us#invisible_recaptcha', as: :new_invisible_recaptcha
  post '/invisible_recaptcha_create', to: 'contact_us#invisible_recaptcha_create', as: :invisible_recaptcha

  get '/contact_us/:id', to: redirect('/thank-you')

  root "contact_us#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_us.rb
class ContactUs < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
	def new
		@contact = ContactUs.new
	end

	def create
		@contact = ContactUs.new(contact_us_params)
		if verify_recaptcha(model: @contact) && @contact.save
		  redirect_to @contact
		else
			flash[:error] = "Please fill captcha"
		  render 'new'
		end
	end

	def show
		@contact = ContactUs.find(params[:id])
	end

	def invisible_recaptcha
		@contact_new = ContactUs.new
	end

	def invisible_recaptcha_create
		@contact_new = ContactUs.new(contact_us_params)
		if verify_recaptcha(model: @contact) && @contact.save
		  redirect_to @contact
		else
			flash[:error] = "Please fill captcha"
		  render 'invisible_recaptcha'
		end
	end
 
	private
  def contact_us_params
    params.require(:contact_us).permit(:name, :email, :company_name, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/views/contact_us/invisible_recaptcha.html.erb
<%= form_for @contact_new, url: invisible_recaptcha_path, html: {id: 'invisible-recaptcha-form'} do |f| %>
  <div class="alert alert-danger" style="color: red;">
    <% if flash[:error].present?%>
      <%= flash[:error]%>
    <%end%>
  </div>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>
  <%= invisible_recaptcha_tags text: 'Submit' %>
<% end %>

<script type="text/javascript"> 
  $(".g-recaptcha").click(function(){
    $("#invisible-recaptcha-form").submit();
  });
</script>

app/views/contact_us/new.html.erb
<%= form_for @contact, url: contact_us_path, html: {id: 'recaptcha-form'} do |f| %>
  <div class="alert alert-danger" style="color: red;">
    <% if flash[:error].present?%>
      <%= flash[:error]%>
    <%end%>
  </div>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, pattern: "((\+*)((0[ -]+)*|(91 )*)(\d{12}+|\d{10}+))|\d{5}([- ]*)\d{6}" %>
  </p>
  <%= recaptcha_tags %>
 
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/additional-methods.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
<script type="text/javascript">
   // jQuery Validation Plugin not working for me. npm and other related tools are not present in my system. So just added the code, plugin is not working for me.
  $( document ).ready(function() {
    $("#recaptcha-form").validate({
        rules: {
          email: {
            required: true,
            email: true
          },
          name: {
            required: true
          },
          phone_number: {
            required: true,
            number: true
          }
        },
        messages:  {
          email: {
            required: "Please enter the email",
            email: "Enter an email"
          },
          name: {
            required: "Please enter the name"
          },
          phone_number: {
            required: "Please enter the name"
          },
        }
    });
    jQuery.validator.setDefaults({
      errorPlacement: function(error, element) {
        error.appendTo(element.prev());
      }
    });
  });
</script>

app/views/contact_us/show.html.erb
<p>Thank you for contacting us. Our team will reach you shortly!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>